elasticsearch:
  build: elasticsearch/
  ports:
    - "9200:9200"

logstash:
  build: logstash/
  links:
    - elasticsearch
  ports:
    - "5000:5000"
    - "5001:5001"
    - "12345:12345"

kibana:
  build: kibana/
  ports:
    - "8080:80"
  links:
    - elasticsearch
    - logstash

suricata:
  build: suricata/
  net: host
  environment:
    - INTERFACE=eth1
    - HOST_UID=$(id -u)
  links:
    - elasticsearch
    - logstash
